# Generated by Django 4.0.2 on 2022-03-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('request_message', models.TextField(blank=True, null=True)),
                ('sent_date', models.DateField(auto_now_add=True)),
                ('accepted_date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
    ]
